polzzak-by-nowashgirls/polzzak

- src/components/Button/button.tsx
<br>
- modify/button/ttining
<br>
- disabled 스타일 수정
- size 수정
- 불필요한 성능 최적화 제거
- 사용 예시
- <Button variant="primary" size="sm"> { children } </Button>
- <Button variant="primary" size="sm" asChild> <Link to="/">링크</Link> </Button>
<br>
<br>
- #12
> [Modify] 버튼 컴포넌트 수정

- src/styles/globals.css
<br>
- modify/css/hyeonju
<br>
- font-weight 네이밍 수정
- 글씨 크기 변경 (13, 14, 15, 16, 18, 40)
```tsx
<h3 className="text-14">예시 텍스트</h3>
```
- 글씨 굵기 변경 (thin(100), extralinght(200), light(300), regular(400), medium(500), semibold(600), bold(700), extrabold(800), black(900)
```tsx
<h3 className="font-semibold">예시 텍스트</h3>
```
- 글씨/배경 등등 변경 (primary, primary-hover, primary-active)
```tsx
<div className="text-primary bg-primary-hover">예시 텍스트</div>
```
<br>
<br>
- #23
> [Modify] global.css 수정

- package.json
- pnpm-lock.yaml
- src/components/Register/RegisterStep.tsx
- src/components/Register/Step.tsx
- src/components/Register/progress.tsx
<br>
- feature/register_step/hyeonju
<br>
- 회원가입 진행도에 따른 progress/step(1, 2, 3, 4, 5)/제목 변경
- 웹 접근성
```tsx
// 예
import RegisterStep from '@/components/Register/RegisterStep';
function Register() {
return (
<div className="px-8 py-6">
<RegisterStep step={1} />
</div>
);
}
export default Register;
```
<br>
<br>
- #21
> [Feature] 회원가입 진행도 컴포넌트

- src/components/Input/Textarea.tsx
<br>
- feature/textarea/yoon -> develop
<br>
- Textarea 컴포넌트 추가
- label, hideLabel은 선택 props
```tsx
<Textarea label="메모" placeholder="메모를 작성해 주세요." />
```
<br>
<br>
- #31
> [Feature] Textarea 컴포넌트

- src/components/Icon/Icon.tsx
<br>
- modify/icon/yoon -> develop
<br>
- 컴포넌트명 변경 (SvgIcon > Icon)
- 함수타입 변경 (const > function)
<br>
<br>
- #41
> [Modify] Icon 컴포넌트 수정

- src/components/Calendar/Calendar.tsx
- src/components/My/MenuItem.tsx
- src/components/Toast.tsx
<br>
- feature/mymenu/ttining
<br>
- 마이페이지 `MenuItem` 컴포넌트 제작
- 달력, 토스트 컴포넌트 수정 (아이콘 컴포넌트 이름 변경 - `SvgIcon` → `Icon`)
```tsx
const menus = [
{ label: '공지사항', href: '/notice' },
{ label: '서비스 이용약관', href: '/terms' },
{ label: '로그아웃', href: '/logout' },
];
<MenuItem menus={menus} />
```
<br>
<br>
- #38
> [Feature] 마이페이지 메뉴 컴포넌트

- src/components/Profile/Profile.tsx
- src/mockData/UserInfo.tsx
- src/mockData/index.ts
<br>
- feature/profile/hyeonju
<br>
- 마이페이지-프로필 컴포넌트 제작
1. 유저이름
2. 유저이메일
3. 편집(내 정보 페이지로 이동)
```tsx
import Profile from '@/components/Profile/Profile';
import { USER_INFO } from '@/mockData';
function Home() {
return (
<div className="px-8 py-6">
<Profile userInfo={USER_INFO} />
</div>
);
}
export default Home;
```
<br>
<br>
- #48
> [Feature] 마이페이지-프로필 컴포넌트

- package.json
- pnpm-lock.yaml
- src/components/Input/Input.tsx
- src/components/Input/RadioGroup.tsx
- src/components/Input/SelectMenu.tsx
- src/components/Label.tsx
- src/lib/dateUtils.ts
- src/mockData/ScheduleDummyData.tsx
<br>
- feature/radio/yoon -> develop
<br>
- 일정 || 즐겨찾기
- 객체를 props로 받음
- Label, Input 컴포넌트 : 스타일 수정
- dateUtils.ts : getTripDays에서 2025.03.15 ~ 2025.03.16 으로 반환 가능
- Input 컴포넌트 : 불필요한 div 삭제
```tsx
{/* 일정 추가 *}
<Radio data={ScheduleDummyData} />
{/* 즐겨찾기 *}
<Radio data={BookmarkDummyData} />
```
<br>
<br>
- #33
> [Feature] Radio 컴포넌트 추가

- src/components/Chip/Chip.tsx
<br>
- feature/chip/hyeonju
<br>
- chip 컴포넌트 제작
- 클릭 시, active 상태 토글
```tsx
import Chip from '@/components/Chip/Chip';
<Chip mode="region" />
<Chip mode="theme" />
```
<br>
<br>
- #52
> [Feature] Chip 컴포넌트

- src/components/Header/Header.tsx
<br>
- feature/header/hyeonju
<br>
- Header 컴포넌트 제작
- 타이틀
- 서브타이틀
- 왼쪽 아이콘 버튼
- 오른쪽 아이콘/텍스트 버튼
- 클릭이벤트
- 링크 이동
```tsx
// 예시
import Header from '@/components/Header/Header';
<Header title="🐰 폴짝 🐰" editHide={true} iconId="search" />
<Header title="회원가입" editHide={true} />
<Header title="검색" subTitle="검색결과 32건" editHide={true} />
<Header title="즐겨찾기" />
<Header title="즐겨찾기" iconId="search" editHide={true} />
/*
1. title : 헤더 제목
2. subTitle : 서브 제목
3.  editHide : 기본값 false, true시 오른쪽 편집 버튼 숨기기
4. iconId : 오른쪽 아이콘 버튼에 들어갈 아이콘id
*/
```
<br>
<br>
- #54
> [Feature] Header 컴포넌트

- src/components/Category/Category.tsx
<br>
- modify/category/hyeonju
<br>
- 수정된 이미지 크기 변경
- 수정된 css에 맞게 className 변경
- 웹접근성, 웹표준성 검사
<br>
<br>
- #63
> [Modify] Category 컴포넌트

- src/components/Calendar/Calendar.tsx
- src/components/Calendar/CalendarCustom.tsx
- src/components/Carousel/Carousel.tsx
- src/components/Icon/Icon.tsx
- src/components/SortDropdown/Dropdown.tsx
- src/components/SortDropdown/DropdownCustom.tsx
<br>
- modify/calendar/ttining
<br>
- 달력 컴포넌트 수정
- 연도 / 월 `formatter` 추가
- range 모드로 변경
- CalendarCustom 컴포넌트 생성
- 아이콘 컴포넌트 수정
- viewBox 속성 추가
- 캐러셀 컴포넌트 수정
- 아이콘 `id` 변경 
- 드롭다운 컴포넌트 파일명 변경
- Sort → DropdownCustom
<br>
<br>
- #72
> [Modify] 달력 컴포넌트 외 다수 수정

- package.json
- pnpm-lock.yaml
- src/components/Checkbox/Checkbox.tsx
<br>
- feature/checkbox/ttining
<br>
- Checkbox 컴포넌트 관련 패키지 추가
- Checkbox 컴포넌트 제작
- 사용 예시
```tsx
<Checkbox id={'saveIdCheck1'} label="아이디 저장" checked={true} />
<Checkbox id={'saveIdCheck2'} label="아이디 저장" />
<Checkbox id={'saveIdCheck3'} label="아이디 저장" srOnly={true} />
```
<br>
<br>
- #80
> [Feature] 체크박스 컴포넌트

- src/components/Modal/AlertModal.tsx
- src/components/Modal/Dimd.tsx
- src/components/Modal/Modal.tsx
- src/components/Modal/SlideUpModal.tsx
- src/hooks/useModalActions.ts
- src/store/useModalStore.ts
<br>
- feature/modal/hyeonju
<br>
- Dimd 컴포넌트 제작
- AlertModal 컴포넌트 제작
```tsx
import Modal from '@/components/Modal/Modal';
<Modal mode="alert" type="certify_success" />
<Modal mode="alert" type="certify_fail" />
<Modal mode="alert" type="register" />
<Modal mode="alert" type="logout" />
<Modal mode="alert" type="delete" />
<Modal mode="alert" type="polzzak_add" />
```
- SlideUpModal 컴포넌트 제작
```tsx
import Modal from '@/components/Modal/Modal';
<Modal mode="slide" type="calendar" />
<Modal mode="slide" type="favorite_add" />
<Modal mode="slide" type="folder_edit" />
<Modal mode="slide" type="folder_delete" />
<Modal mode="slide" type="polzzak_add-new" />
<Modal mode="slide" type="polzzak_add-exist" />
<Modal mode="slide" type="polzzak_edit" />
<Modal mode="slide" …
```
> [Feature] Modal 컴포넌트

- src/components/Header/Header.tsx
- src/components/NavMenu/NavMenu.tsx
- src/layouts/RootLayout.tsx
- src/styles/globals.css
<br>
- feature/layout/ttining
<br>
- RootLayout 설정 및 글로벌 css 수정
- Header 컴포넌트 수정
- `iconId` 타입 변경 및 클래스 추가
- NavMenu 컴포넌트 수정
- `className` 프롭스 및 클래스 추가
<br>
<br>
- #87
> [Feature] RootLayout 설정

- src/components/HomeThemes/HomeThemes.tsx
- src/components/HomeThemes/ThemeItemListCard.tsx
- src/mockData/ListItemDummyData.tsx
<br>
- feature/themes-section/yoon -> develop
<br>
- 홈 테마 섹션 컴포넌트
- HomeThemes 컴포넌트의 props인 data로 "THEMES_ITEM_DUMMY_DATA[0]" 임시로 지정. 추후 수정 필요
- THEMES_ITEM_DUMMY_DATA 추가
- 예시) `<HomeThemes data={} />`
<br>
<br>
- #85
> [Feature] 홈 테마 섹션 컴포넌트 제작

- src/components/Input/SelectMenu.tsx
<br>
- modify/select/yoon -> develop
<br>
- 이메일 셀렉트 사용 가능하도록 수정 
- 이메일 : `<SelectMenu data={'email'} />`
- 날짜 : `<SelectMenu data={날짜데이터} />`
<br>
<br>
- #98
> [Modify] 셀렉트메뉴 컴포넌트 수정

- src/components/Chip/Chip.tsx
- src/components/Input/Input.tsx
- src/components/Modal/Dimd.tsx
- src/components/Modal/SlideUpModal.tsx
- src/layouts/RootLayout.tsx
- src/pages/Polzzak/Add/Add.tsx
- src/pages/Polzzak/Polzzak.tsx
- src/pages/Polzzak/index.ts
- src/router.tsx
<br>
- feature/polzzak/hyeonju
<br>
- Refactor
- Chip 컴포넌트 → 지역/테마선택, 단일/다중선택 제목 생성
- Modify
- Input 컴포넌트 → margin값 수정(px-2 → px-1)
- Feature
- 폴짝 페이지 레이아웃(리스트가 있을경우, 없을경우)
- 폴짝 추가 페이지
- 폴짝 날짜 아이콘 선택 시 폴짝 날짜 모달 출력
- 폴짝 router 추가
<br>
<br>
- #101
> [Feature] 폴짝 페이지

- src/components/Register/RegisterStep.tsx
- src/hooks/useModalActions.ts
- src/layouts/RootLayout.tsx
- src/pages/Register/Register.tsx
- src/pages/Register/Step1.tsx
- src/pages/Register/Step2.tsx
- src/pages/Register/Step3.tsx
- src/pages/Register/Step4.tsx
- src/pages/Register/Step5.tsx
- src/pages/Register/StepPage.tsx
- src/pages/Register/index.ts
- src/router.tsx
<br>
- feature/join-layout/yoon -> develop
<br>
- Register에서 하위 경로 받음
- StepPage에서 각 스텝에 맞는 경로 확인
- 각 스텝별로 페이지 생성
- index.ts로 함수 모음
- 회원가입 페이지를 만들면서 각종 파일 수정
<br>
<br>
- #93
> [Feature] 회원가입 페이지 레이아웃 제작

- src/pages/My/Edit/index.ts
- src/router.tsx
<br>
- modify/mypage/hyeonju → develop
<br>
- 마이페이지 라우터 수정
<br>
<br>
- #107
> [Modify] 마이페이지

- src/components/Contents/Details.tsx
- src/layouts/RootLayout.tsx
- src/pages/Contents/Contents.tsx
- src/pages/Contents/ViewDetails.tsx
- src/pages/Register/StepPage.tsx
- src/pages/index.ts
- src/router.tsx
<br>
- feature/details/yoon -> develop
<br>
- 목록 상세보기 페이지 레이아웃(id 필요)
- RootLayout : isContentsPath 수정 필요
<br>
<br>
- #117
> [Feature] 목록 상세 레이아웃

- src/components/BookmarkFolder/AddBookmarkFolder.tsx
- src/components/BookmarkFolder/BookmarkFolder.tsx
- src/components/BookmarkFolder/BookmarkFolderCard.tsx
- src/components/BookmarkFolder/BookmarkFolderList.tsx
- src/components/Header/Header.tsx
- src/components/UserMenu/UserMenu.tsx
- src/layouts/RootLayout.tsx
- src/pages/My/Bookmark.tsx
- src/pages/My/My.tsx
- src/pages/index.ts
- src/router.tsx
- src/store/useModalStore.ts
<br>
- feature/favorite/ttining → develop
<br>
- My → 즐겨찾기 경로 추가
- 페이지 레이아웃
- `Header` 컴포넌트 : `mode` 추가 (`searchParams`)
- `Modal` 핸들러 추가 및 프롭스 드릴링
- `useModalStore` 내 `Type` 추가
<br>
<br>
- #116
> [Feature] 즐겨찾기 레이아웃

- src/components/Timeline/TimelineList.tsx
- src/components/Timeline/TimelineSchedule.tsx
- src/mockData/PolzzakItemDummyData.tsx
- src/mockData/PolzzakListDummyData.tsx
- src/pages/Polzzak/Schedule/Schedule.tsx
- src/pages/Polzzak/index.ts
- src/router.tsx
<br>
- feature/polzzak-details/yoon -> develop
<br>
- 헤더 추후에 수정 필요
- 임시 더미데이터 수정
- TimelinsSchedule 컴포넌트 제작
- TimelineList 컴포넌트 수정
<br>
<br>
- #118
> [Feature] 폴짝 상세 레이아웃

- src/components/ListItem/ListItem.tsx
- src/pages/NotFound.tsx
- src/pages/Search/SearchResult.tsx
- src/router.tsx
- src/vite-env.d.ts
<br>
- feature/list/yoon -> develop
<br>
- 목록 레이아웃 제작
- ListItem : Link 태그 추가
<br>
<br>
- #106
> [Feature] 목록 레이아웃

- src/components/Input/Input.tsx
- src/components/Input/Select.tsx
- src/components/Input/Textarea.tsx
- src/layouts/RootLayout.tsx
- src/pages/Contents/ViewDetails.tsx
- src/pages/Polzzak/Schedule/Schedule.tsx
- src/store/useHeaderStore.ts
<br>
- modify/root-layout/yoon-> develop
<br>
- zustand로 헤더 타이틀 변경하는 store함수 생성
<br>
<br>
- #128
> [Modify] 데이터별 헤더 타이틀 변경

- src/components/Button/ButtonVariants.tsx
- src/components/SortDropdown/Dropdown.tsx
- src/components/SortDropdown/DropdownCustom.tsx
<br>
- fix/sort/ttining → develop
<br>
- 정렬 드롭다운 컴포넌트 수정
- `preventDefault` 관련 오류 해결
- 드래그 관련 이벤트 핸들러 추가
- 버튼 컴포넌트 수정
- `margin` 속성 제거
<br>
<br>
- #122
> [Fix] 정렬 드롭다운 컴포넌트 이슈 해결

- src/api/openAPI/index.ts
- src/api/openAPI/useGetAreaCode.ts
<br>
- chore/openapi/hyeonju → develop
<br>
- open API 세팅
- 지역코드조회 함수 생성 (배열로 출력)
```tsx
import { useGetAreaCode } from '@/api/openAPI';
const areaCodeList(임의의 변수명) = useGetAreaCode();
console.log(areaCodeList);
```
<br>
<br>
- #133
> [Chore] open API 세팅 및 함수 생성

- src/components/Button/ButtonVariants.tsx
- src/components/Input/Input.tsx
- src/components/Input/Select.tsx
- src/components/Input/Textarea.tsx
- src/components/Modal/AlertModal.tsx
- src/pages/My/Edit/Email/Email.tsx
- src/pages/My/Edit/NickName/NickName.tsx
- src/pages/My/Edit/Password/Password.tsx
- src/pages/NotFound.tsx
- src/pages/Register/Step3.tsx
- src/pages/Register/Step5.tsx
- src/pages/Search/Search.tsx
<br>
- modify/page-layout/yoon -> develop
<br>
- 컴포넌트 마진 제거로 레이아웃 수정
<br>
<br>
- #134
> [Modify] 레이아웃 수정

- src/api/openAPI/hooks/useGetDetailPetTour.ts
<br>
- feature/pet-data/ttining → develop
<br>
- Tour API 반려동물 동반 여행 정보 데이터 가져오기 (`useGetDetailPetTour.ts` hook 생성)
<br>
<br>
- #137
> [Feature] 반려동물 동반 여행 정보 데이터 가져오기

- src/api/openAPI/hooks/useGetCategoryCode.ts
- src/api/openAPI/hooks/useGetDetailPetTour.ts
<br>
- feature/category-code/ttining → develop
<br>
- Tour API '서비스 분류 코드 조회' 데이터 가져오기 (`useGetCategoryCode.ts` hook 생성)
- 반려동물 동반 여행 정보 훅 수정
- `PetTourItemType` 추가
- 초기값 추가 및 조건문 제거
<br>
<br>
- #139
> [Feature] 서비스 분류 코드 조회 데이터 가져오기

- src/api/openAPI/hooks/useGetAreaCode.ts
- src/api/openAPI/hooks/userGetDetailCommon.ts
- src/api/openAPI/index.ts
- tsconfig.app.json
<br>
- feature/openapi/hyeonju → develop
<br>
- openAPI 공통 정보 조회
```
import { useGetDetailCommon } from '@/api/openAPI';
const details = useGetDetailCommon(지역코드);
console.log(details);
```
- openAPI 지역 코드 조회 리팩토링
- import.meta.env 오류 수정
<br>
<br>
- #140
> [Feature] openAPI 공통 정보 조회

- src/components/Chip/Chip.tsx
- src/components/MapHeader/MapHeader.tsx
- src/components/Modal/Dimd.tsx
- src/components/Modal/SlideUpModal.tsx
- src/layouts/RootLayout.tsx
- src/pages/Map/Map.tsx
- src/router.tsx
- src/store/useModalStore.ts
<br>
- feature/map/hyeonju → develop
<br>
- 지도 페이지 레이아웃 생성
- Chip 컴포넌트 수정
- MapHeader 분리 
<br>
<br>
- #103
> [Feature] 지도 페이지 레이아웃

- src/api/openAPI/hooks/useGetFestival.ts
- src/layouts/RootLayout.tsx
<br>
- feature/festival-fetch/yoon -> develop
<br>
- Tour API 행사 정보 데이터 가져오기
<br>
<br>
- #141
> [Feature] 행사 정보 데이터 가져오기

- src/components/Modal/AlertModal.tsx
- src/hooks/useModalActions.ts
- src/lib/validatePassword.ts
- src/lib/validationId.ts
- src/pages/Login/Login.tsx
- src/store/useModalStore.ts
- src/styles/globals.css
<br>
- feature/login/ttining
<br>
- 아이디, 비밀번호 유효성 검사
- 아이디 저장 체크 후 로그인 버튼 클릭 시 로컬 스토리지에 저장
- 로그인 실패 시 모달 출력
- 로그인 성공 시 home 화면으로 이동
<br>
<br>
- #145
> [Feature] 로그인 기능 구현

- src/components/Chip/Chip.tsx
<br>
- refactor/chip/hyeonju → develop
<br>
- label, subLabel 추가
- Button 추가
- 단일선택시 toggle 기능 안되던 오류 수정
```tsx
import Chip from '@/components/Chip/Chip';
<Chip mode="region" label="지역 선택" subLabel="단일 선택" type="default" onClick={} />
<Chip mode="theme" label="테마 선택" subLabel="다중 선택" type="multiple" onClick={} />
<Chip mode="map_filter" onClick={} />
```
<br>
<br>
- #154
> [Refactor] Chip 컴포넌트

- src/components/Dialog/AlertDialog.tsx
- src/components/Dialog/SlideUpDialog.tsx
- src/store/useModalStore.ts
<br>
- feature/dialog/yoon -> develop
<br>
사용예시
```tsx
function Example() {
const { isOpen } = useModalStore();
const modalBtn = [
{
text: '취소',
},
{
text: '확인',
onClick: () => {
console.log('확인');
},
},
];
const modalDesc = ['첫 번째 설명', '두 번째 설명'];
return (
<main className="p-6">
{isOpen && (
<SlideUpDialog header="타이틀 들어가용" button={modalBtn}>
<div>여기에 아무거나 넣을 수 있어요!</div>
</SlideUpModal222>
)}
{isOpen && (
<AlertDialog header="타이틀 들어가용" button={modalBtn} description={modalDesc} />
)}
</main>
);
}
```
<br>
<br>
- #159
> [Feature]  Dialog 컴포넌트 제작

- src/components/Dialog/AlertDialog.tsx
- src/components/Dialog/SlideUpDialog.tsx
- src/store/useDialogStore.ts
- src/store/useModalStore.ts
<br>
- modify/dialog/yoon
<br>
- useDialogStore 생성
- 스토어 함수 변경 및 props 추가
<br>
<br>
- #161
> [Modify] Dialog 컴포넌트 수정

- src/api/supabase/hooks/updateEmail.ts
- src/api/supabase/hooks/updateNickname.ts
- src/components/Profile/Profile.tsx
- src/hooks/useModalActions.ts
- src/mockData/UserInfo.tsx
- src/mockData/index.ts
- src/pages/My/Edit/Edit.tsx
- src/pages/My/Edit/Email/Email.tsx
- src/pages/My/Edit/NickName/NickName.tsx
- src/pages/My/Edit/Password/Password.tsx
- src/pages/My/Edit/PhoneNumber/PhoneNumber.tsx
- src/pages/My/My.tsx
- src/store/useEditStore.ts
- src/store/useModalStore.ts
- src/store/usePasswordStore.ts
- src/store/useUserStore.ts
<br>
- feature/mypage/hyeonju → hyeonju
<br>
1. 비로그인 일 경우 RequireLogin 페이지 출력
2. 프로필 편집
- 닉네임 설정
- 비밀번호 설정
- 휴대폰 번호 설정
- 이메일 설정
3. 탈퇴하기 기능
4. 로그아웃 기능
<br>
<br>
- #165
> [Feature] 마이페이지 기능

- src/layouts/RootLayout.tsx
- src/lib/validationEmail.ts
- src/pages/Login/FindId.tsx
- src/pages/Login/Login.tsx
- src/pages/Login/ResetPassword.tsx
- src/pages/Login/ResetPasswordCallback.tsx
- src/pages/index.ts
- src/router.tsx
- src/store/useDialogStore.ts
- src/styles/globals.css
<br>
- `feature/find-auth/ttining` → `develop`
<br>
- 로그인 페이지 수정
- 모달 → 다이얼로그 컴포넌트로 변경
- 아이디 찾기 기능 구현
- 비밀번호 재설정 기능 구현
<br>
<br>
- #178
> [Feature] 아이디, 비밀번호 찾기 기능 구현

- src/components/Dialog/SlideUpDialog.tsx
- dragIcon이 true일 경우에만 height 기본값 적용
<br>
- modify/dialog/ttining -> develop
<br>
- `dragIcon`이 `true`일 경우에만 `height` 기본값 적용
<br>
<br>
- #182
> [Modify] 다이얼로그 컴포넌트 수정

- src/api/openAPI/utils/fetchContentDetail.ts
- src/components/Map/DetailItems.ts
- src/components/Map/ModalContent.tsx
- src/components/Map/ModalDetailContent.tsx
- src/lib/formatBr.tsx
- src/lib/formatDate.ts
- src/pages/Map/Map.tsx
- src/types/categoryDetailType.ts
<br>
- feature/map/ttining → develop
<br>
- 다이얼로그 수정
- `ListItemCardById` 사용
- 리스트 아이템 컴포넌트 사용
- 우선 순위 조절 및 카테고리 변경 시, 상태 초기화
- 마커 클릭 시 다이얼로그 내용 변경
- `fetchContentDetail` 수정
- API 호출 시, `response` 객체 방어 코드 추가
- 모달 상세 내용 추가
- `DetailItems`, `categoryDetailTypes` 및 유틸 함수 추가
<br>
<br>
- #184
> [Feature] 지도 페이지 기능 구현

- src/components/Calendar/CalendarCustom.tsx
- src/components/Input/Input.tsx
- src/components/Timeline/Plan.tsx
- src/components/Timeline/TimelineCard.tsx
- src/components/Timeline/TimelineList.tsx
- src/components/Timeline/TimelineSchedule.tsx
- src/pages/Polzzak/Schedule/AddPlan/AddPlan.tsx
- src/pages/Polzzak/Schedule/Schedule.tsx
- src/pages/Polzzak/index.ts
- src/router.tsx
<br>
- feature/polzzak/yoon -> develop
<br>
- 일정 추가 및 편집 시 UI 바로 변경
- 편집 버튼 클릭 시, 순서 변경 및 편집 가능
- 편집 버튼 클릭하지 않아도 편집모달은 뜨도록
- Tanstack Query로 캐시하도록 구현
- 일정 추가 시 장소 직접 작성 가능 (지도로 이동 후 선택 기능은 추후 구현 예정)
<br>
<br>
- #181
> [Feature] 폴짝 페이지 기능 완료 (지도에서 장소 저장 제외)

- src/api/openAPI/hooks/useGetFestival.ts
- src/components/Favorites/FavoritesList.tsx
- src/components/ListItem/ListItemCardById.tsx
- src/pages/Polzzak/AddNEdit/AddNEdit.tsx
- src/pages/Polzzak/Polzzak.tsx
- src/pages/Search/SearchResult.tsx
<br>
- fix/yoon -> develop
<br>
- 에러내용 수정
<br>
<br>
- #192
> [Fix] 린트 결과 수정

- src/api/openAPI/utils/fetchContentDetail.ts
- src/components/Dialog/SlideUpDialog.tsx
- src/components/Map/MapHeader.tsx
- src/components/Map/ModalDetailContent.tsx
<br>
- fix/ttining → develop
<br>
- 린트 오류 수정
- `SlideUpDialog`, `ModalDetailContent`, `fetchContentDetail`, `MapHeader`
<br>
<br>
- #191
> [Fix] 린트 오류 수정
